context:
  version: "1.4.0"

package:
  name: pta
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/pta/-/pta-${{ version }}.tgz
  sha256: 05f2f755f62ac8969173c8ba9ff5b48bf0830c74ac1413ee6ed76fa8c6e72abd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - pta --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Test runner for nodejs using zora
  homepage: https://github.com/lorenzofox3/zora
  repository: https://github.com/lorenzofox3/zora

extra:
  recipe-maintainers:
    - danielnachun
